baseURL: 'https://woodcock3.github.io/hatstack'
languageCode: en
title: Hatstack
theme: hatstack
paginate: 100
defaultContentLanguage: en
markup:
    goldmark:
        renderer:
          unsafe: true
permalinks:
  pages: /:slug/
  
