name: Deploy Hugo

on:
  schedule:
    # run daily at 05:30
    - cron:  '30 5 * * *'
  push:
    branches: 
      - main
    paths-ignore:
      - 'README.md'
# Conditional environmental if's      
env:
  UPDATE_NPM: false # false = deploy jekyll , true boolean = update npm
      
# Build site using Hugo
jobs:
  hugo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      # condition - if UPDATE_NPM = false
      - run: echo ${{ env.UPDATE_NPM }}
        if: env.UPDATE_NPM != 'true'
        # checkout code
      - name: Get latest code
        if: env.UPDATE_NPM != 'true'
        uses: actions/checkout@v2.3.4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        if: env.UPDATE_NPM != 'true'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: npm install
        if: env.UPDATE_NPM != 'true'
        run: npm run build

      - name: Build minified
        if: env.UPDATE_NPM != 'true'
        run: hugo --environment production --minify
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        if: env.UPDATE_NPM != 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          # GITHUB_TOKEN secret is set up automatically
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


  # Update NPM if env.UPDATE_NPM = true
  npm-update:
    name: npm update
    runs-on: ubuntu-latest
    steps:
      # condition - if UPDATE_NPM = true
      - run: echo '${{ env.UPDATE_NPM }}'
      - name: Checkout
        if: env.UPDATE_NPM == 'true'
        uses: actions/checkout@v2
      - name: Setup Node
        if: env.UPDATE_NPM == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm init -y
        if: env.UPDATE_NPM == 'true'
      - run: npm install
        if: env.UPDATE_NPM == 'true'
      # - run: npm uninstall @11ty/eleventy alpinejs html-minifier npm-run-all tailwindcss @builder.io/partytown @tannerhodges/snap-slider
      # - run: npm update # update packages
      - name: pull request on npm update
        if: env.UPDATE_NPM == 'true'
        uses: woodcock3/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates
  
            Auto-generated by [create-pull-request][1]
  
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
